basePath: /
consumes:
    - application/json
info:
    description: '# Documentation for product API'
    title: of product API
    version: 1.0.0
paths:
    /createProduct:
        post:
            description: Creates the new product
            operationId: createNewProduct
            responses:
                "200":
                    $ref: '#/responses/productResponse'
            tags:
                - createProduct
    /deleteProduct/{id}:
        delete:
            description: Removes the product based of Id
            operationId: Delete
            tags:
                - removeProduct
    /products:
        get:
            description: Returns a list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/prodcutsResponse'
            tags:
                - products
    /products/{id}:
        put:
            description: Creates the new product by id
            operationId: updateExistingProduct
            responses:
                "200":
                    $ref: '#/responses/productResponse'
            tags:
                - updateProduct
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
